### ISSUE TITLE
cookie usage

### ISSUE THREAD

**Issue by bonchianglee** [sabre-io/http#102]
May I know any future development or current usage of cookie in sabreio/http?

**Comment by DeepDiver1975** [comment]
Why are you opening this again?
This hast been answered in #101 - right?

**Comment by evert** [comment]
Hi @bonchianglee ,

I think it's unlikely that there will be native support for cookies directly embedded into sabre/http classes. Cookies are just 2 more headers (`Set-Cookie` and `Cookie`), so it doesn't make a ton of sense to further expand the Request and Response headers with specific API's for this.

However, I don't see a reason why we couldn't ship a parsers for these headers in `lib/functions.php`. We do this for a number of other headers, so it makes sense to me to add them there.

However, this library is mostly used outside of 'Web' contexts, so if you like this feature, the best thing you can do is contribute it via a pull request.

**Comment by evert** [comment]
Closing this issue as I think it's answered, but feel free to follow-up here with more questions.
