### ISSUE TITLE
 Uncaught Error: Class 'Sabre\HTTP\URLUtil' not found

### ISSUE THREAD

**Issue by Offerel** [sabre-io/http#104]
If using release 5.0.0 with sabre/uri 2.1.0 and sabre/event 5.0.3 i get the following error " Uncaught Error: Class 'Sabre\HTTP\URLUtil' not found".

**Comment by DeepDiver1975** [comment]
did you clone the repo or use composer? Please list instructions and maybe a code snippet.

I'm damn sure this is a local issue on your installation.

**Comment by Offerel** [comment]
I used sabreDAV 3.2.2 from the release.tar.gz of GitHub. Then I loaded the latest release.tar.gz of sabre/uri and sabre/event from GitHub and overwrote the directories of sabreDAV 3.2.2. Up to and including sabre/http 4.2.2 this also worked.

I can't install composer on my Rasperry Pi.  If I use the package from the Raspbian repository, the version seems to be out of date. So at least corresponding error messages. Attempts to build Composer from source don't work either, here the felt billions of dependencies are not fulfilled and I should install additional programs, but I don't want to do that at all.

**Comment by Offerel** [comment]
I have downloaded composer.phar to /tmp and called it now with "sudo -u www-data php /tmp/composer.phar install" in the directory where i have unpacked sabre/http. It starts to install things, where i dont know what they are for. For example:

```
  - Installing symfony/stopwatch (v3.4.14): Downloading (100%)
  - Installing symfony/process (v3.4.14): Downloading (100%)
  - Installing symfony/finder (v3.4.14): Downloading (100%)
  - Installing symfony/polyfill-ctype (v1.9.0): Downloading (100%)
  - Installing symfony/filesystem (v3.4.14): Downloading (100%)
  - Installing symfony/event-dispatcher (v3.4.14): Downloading (100%)
  - Installing psr/log (1.0.2): Downloading (100%)
  - Installing symfony/debug (v3.4.14): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.9.0): Downloading (100%)
  - Installing symfony/console (v3.4.14): Downloading (100%)
  - Installing sebastian/diff (1.4.3): Downloading (100%)
  - Installing friendsofphp/php-cs-fixer (v1.11.8): Downloading (100%)
```
I have killed this process now, since I really don't want any unknown things on my server. Is there no other way to install sabre/http as this composer thing? I didn't want to use this.

**Comment by DeepDiver1975** [comment]
you are installing development dependencies - use --no-dev option - see https://getcomposer.org/doc/03-cli.md#install-i

**Comment by DeepDiver1975** [comment]
> Is there a way to check, which version of the components like sabre/http, sabre/event, etc. is actual used by sabre/dav? Maybe some http request or command line parameter or anything else?

this is exactly the job of composer. composer is a dependency manager and pulls in compatible versions of depending libraries.

I'm closing this for now. Enjoy!

**Comment by evert** [comment]
@Offerel  you don't need to actually install all packages individually, you can just install the sabre/dav package. the Composer command will automatically install its depdendencies. Just read `composer.json` to see which versions it needs.

**Comment by Offerel** [comment]
Many thx for the helping hand. i should really check composer and it's parameters for the future work.
