### ISSUE TITLE
Unknown scalar type

### ISSUE THREAD

**Issue by mrcnpdlk** [sabre-io/http#112]
After upgrade to 5.0 my IDE (PHP Storm) shows me a warning:
`Expected \Sabre\HTTP\scalar, got string 
Inspection info: Invocation parameter types are not compatible with declared.`

https://github.com/sabre-io/http/blob/3577f014fe188572386903722e2a78ad6ad45e7e/lib/Message.php#L223

In the previous version (4.2) type was defined as `string|string[]`

**Comment by DeepDiver1975** [comment]
Feel free to submit a pull request too fix this - THX

**Comment by mrcnpdlk** [comment]
I will fix it in the evening. Thanks

**Comment by kesselb** [comment]
Looks like this was fixed by https://github.com/sabre-io/http/pull/192
