### ISSUE TITLE
uplift php min version to 7.2 -> create 6.x version

### ISSUE THREAD

**Issue by staabm** [sabre-io/http#140]
- [ ] increase major to 6.x
- [x] update min php version in composer.json, cleanup travis.yml https://github.com/sabre-io/http/pull/142
- [x] update phpunit to ^8.0 https://github.com/sabre-io/http/pull/142
- [ ] update other depenencies required?

**Comment by staabm** [comment]
anyone aware of other BC-breaking tasks we should focus on for the next major?

**Comment by C0pyR1ght** [comment]
remove non-standard bin-dir from composer.json:

https://github.com/sabre-io/http/blob/68464274ac171b35e137eddd4e9f3a0873b97407/composer.json#L46-L48

**Comment by C0pyR1ght** [comment]
* [ ]  increase major to 6.x
* [x]  update min php version in composer.json
* [x]  update phpunit to ^8.0 #142
* [ ]  update other depenencies required?

done in #142

**Comment by staabm** [comment]
Correct, we resolved it. Thx
