### ISSUE TITLE
undefined function Sabre\\HTTP\\mb_detect_encoding()

### ISSUE THREAD

**Issue by mr-doomy** [sabre-io/http#151]
Hello,

I don't know if this is the right place to post that, but I'm currently trying to set up a CalDAV server using sabre/dav/calendarserver.php with apache2. When I enter the URL in a browser, it does nothing but "displaying" a blank page. So if i go to the apache error log file, I get this:
`PHP Fatal error:  Uncaught Error: Call to undefined function Sabre\\HTTP\\mb_detect_encoding() in /var/www/sabredav/vendor/sabre/http/lib/functions.php:434\nStack trace:\n#0 /var/www/sabredav/vendor/sabre/http/lib/functions.php(421): Sabre\\HTTP\\decodePathSegment('/calendarserver...')\n#1 /var/www/sabredav/vendor/sabre/http/lib/URLUtil.php(59): Sabre\\HTTP\\decodePath('/calendarserver...')\n#2 /var/www/sabredav/vendor/sabre/dav/lib/DAV/Server.php(379): Sabre\\HTTP\\URLUtil::decodePath('/calendarserver...')\n#3 /var/www/sabredav/vendor/sabre/dav/lib/DAV/Server.php(349): Sabre\\DAV\\Server->guessBaseUri()\n#4 /var/www/sabredav/vendor/sabre/dav/lib/DAV/Server.php(253): Sabre\\DAV\\Server->getBaseUri()\n#5 /var/www/sabredav/calendarserver.php(80): Sabre\\DAV\\Server->exec()\n#6 {main}\n  thrown in /var/www/sabredav/vendor/sabre/http/lib/functions.php on line 434`

I'm using:
    - PHP 7.3.19-1~deb10u1
    - the latest sabre/* versions
    - Apache/2.4.38 (Raspbian)

Any idea on the problem? Let me know if you need more intel.

**Comment by staabm** [comment]
I guess this means you php is missing the mb_* functions/extension

https://www.php.net/manual/en/function.mb-detect-encoding.php

**Comment by mr-doomy** [comment]
There is 2 people in this room, 1 smart, 1 dumb. Guess who's who!

I've seen your link to php manuel already, but I did not find which package I had to install. Of course it is the mbstring one...

Now I can see my page ! Thank you pal!
