### ISSUE TITLE
Avoid MD5 as default hashing method

### ISSUE THREAD

**Issue by joh2511** [sabre-io/http#152]
MD5 is cryptographically broken and unsuitable for further use. Please do not use it as default built-in hashing for validation of passwords.

See also: https://www.php.net/manual/en/faq.passwords.php#faq.passwords.fasthash

**Comment by staabm** [comment]
I guess you are refering to the digest auth mechnism.

we cannot change to a different hasing alogrithm because md5 is defined by a spec for this auth method.
it does not support anything else.
