### ISSUE TITLE
Configuration in Sapi.php involved with php-fpm processes produced by playing large video files.

### ISSUE THREAD

**Issue by matsushita-shuya** [sabre-io/http#214]
When I play large video files, moving seekbar of those files or loading a number of thumbnails of photos php-fpm processes stay and don't disappear. It caused php error saying "server reached php-max_children" and timeout.
This will be solved by changing a configuration ```if ($copied <= 0) {``` to ```if ($copied <= 0 || connection_aborted()) {``` in a file named Sapi.php.

**Comment by DeepDiver1975** [comment]
Feel free to open a pull request. THX

**Comment by phil-davis** [comment]
Please check PR #207 - I think that this probably already does what you need.
That changed has been released as a bugfic patch release 5.1.7 6.0.1 and 7.0.2
Upgrade to one of those and see if your problem is fixed.

**Comment by matsushita-shuya** [comment]
Thank you for your Replying!
