### ISSUE TITLE
Question: Allowed memory size

### ISSUE THREAD

**Issue by gasparyanyur** [sabre-io/http#82]
I am using sabre\dav and sabre\client to send large files to another host, but the response I have got the following error

> Allowed memory size of 134217728 bytes exhausted (tried to allocate 31860068 bytes)

I have investigated and have found that the error comes from `Sabre\HTTP\Client:499`

```
$headerBlob = substr($response, 0, $curlInfo['header_size']);
$responseBody = substr($response, $curlInfo['header_size']) ?: null;
```

**Comment by staabm** [comment]
initial discussion at https://github.com/fruux/sabre-dav/issues/975

**Comment by staabm** [comment]
repro-code see https://github.com/fruux/sabre-dav/issues/975#issuecomment-311397084

**Comment by staabm** [comment]
did you try not calling `$response->getBodyAsString(),` as this reads the whole file into memory..?

the data should be streamed into your destination instead beeing loaded as a whole into php memory.

**Comment by gasparyanyur** [comment]
What I need to use instead of ?

**Comment by staabm** [comment]
at best `getBodyAsStream()` and use the resource handle you get with regular php IO functions.

**Comment by evert** [comment]
I think you might have a problem with using streams in the client. THis was never completed. See #15

**Comment by gasparyanyur** [comment]
@staabm  I have used getBodyAsStream() but the problem doesn't solve, because  when I am sending GET method , as a response I am getting error, So the error comes from  Client.php on line 499, when trying to get response body from string.
