### ISSUE TITLE
Make php-curl required

### ISSUE THREAD

**Issue by v-vodyanov** [sabre-io/http#88]
I think composer should alert you, when you're installing this package and don't have php-curl extension installed, cause if you don't, that causes weird behaviour while creating Sabre\HTTP\Client.

**Comment by staabm** [comment]
Curl is only required when using the Client class. All other classes dont require it.

Therefore we only declare it a suggested dependency
https://github.com/sabre-io/http/blob/af4612a22538ce7c664207bcfcffb877594aea48/composer.json#L19

What kind of weird behavior do you mean exactly?

**Comment by v-vodyanov** [comment]
Sorry for the late answer - weird behaviour in my case is, some kind of error throwing on asking curl constant (CURLOPT_RETURNTRANSFER if I remember correctly), but not catchable and that is not causing fatal error and request is continuing execution from some other place. maybe that's something in the Laravel, but that's it - on meeting the line with curl constant, it just going up skipping some levels of call stack and going further.

I guess you're right about suggested dependency and library user of Client class should require ext-curl indeed.
