### ISSUE TITLE
Proposal: tag PHP7+ version 5.0.0

### ISSUE THREAD

**Issue by iammattcoleman** [sabre-io/http#90]
Recent commits have switched to PHPUnit 6.x, which is only for PHP >=7.0. Can you tag a 5.0.0 release that officially drops PHP 5 support?

**Comment by DeepDiver1975** [comment]
@staabm shall we?

**Comment by staabm** [comment]
I guess we can tag a alpha release.

as this will be a new major I would wait a bit, as we could add some further BC breaks before 5.0 is released.
I am not sure yet if we have topics which require BC breaks right now though.

**Comment by DeepDiver1975** [comment]
so let me create a 5.0 branch and we release an alpha and see what happens ....

we only release this to packagist - right?

**Comment by staabm** [comment]
I dont think we need a branch before we got a stable release. just release from master (which already points to 5.0-alpha)

**Comment by DeepDiver1975** [comment]
ok

**Comment by DeepDiver1975** [comment]
here we go - https://github.com/sabre-io/http/releases/tag/5.0.0-alpha1

**Comment by DeepDiver1975** [comment]
... and on packagist: https://packagist.org/packages/sabre/http#5.0.0-alpha1

**Comment by iammattcoleman** [comment]
Thanks!
